github.com:
    oauth_token: placeholder-overwritten-by-network-broker
    git_protocol: https
    user: ts-rogue-eve-github[bot]
    users:
        ts-rogue-eve-github[bot]:
            oauth_token: placeholder-overwritten-by-network-broker
